train_file: ['data/finetune/nlvr_train.json']
val_file: ['data/finetune/nlvr_dev.json']
test_file: ['data/finetune/nlvr_test.json']

image_root: 'images/nlvr2/' # change this to your nlvr image root

## VLMO
vlmo_config: 'configs/config_vlmoB_base64.json'

image_res: 384
patch_size: 16

## Text Encoder
use_roberta: False
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size: 16
augmentation: null

## Other Settings
optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: cos, lr: 5e-5, epochs: 10, num_warmup_steps: 0.2}
accelerator: {SYNCBN: false, FP16_OPT_LEVEL: O1, FP16_LOSS_SCALE: null, RNG_SEED: 42, GRAD_ACCUMULATE_STEPS: 1, CLIP_GRAD_NORM: 3.0}