train_file:  ['data/finetune/flickr30k_train.json']
val_file: 'data/finetune/flickr30k_val.json'
test_file: 'data/finetune/flickr30k_test.json'
image_root: 'images/' # change this to your flickr30k image root


## VLMO
vlmo_config: 'configs/config_vlmoB_base64k.json'

image_res: 384
patch_size: 16

## Text Encoder
use_roberta: False
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size_train: 18
batch_size_test: 12
batch_size_test_text: 256
max_tokens: 40
embed_dim: 256
temp: 0.07
k_test: 128
itc_type: ['fusion']
rerank: False


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}
accelerator: {SYNCBN: false, FP16_OPT_LEVEL: O0, FP16_LOSS_SCALE: null, RNG_SEED: 42, GRAD_ACCUMULATE_STEPS: 1, CLIP_GRAD_NORM: 1.0}